language: julia
os:
  - linux
  - osx
julia:
  - release
  # - nightly
notifications:
  email: false
# uncomment the following lines to override the default test script
#script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("Impute"); Pkg.test("Impute"; coverage=true)'
after_success:
  # push coverage results to CodeCov
  - julia -e 'cd(Pkg.dir("Etcd")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  # build documentation
  # - julia -e 'Pkg.add("Documenter")'
  # - julia -e 'cd(Pkg.dir("Etcd")); include(joinpath("docs", "make.jl"))'
